# [target.riscv32imc-unknown-none-elf]
# runner = "espflash flash --monitor"

[target.riscv32imc-unknown-none-elf]
runner = "probe-rs run --chip esp32c3"

[target.thumbv7m-none-eabi]
runner = "probe-rs run --chip STM32F103C8"

[build]
rustflags = [
  # Required to use defmt
  "-C", "link-arg=-Tdefmt.x",
  # "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-TLink.x",
]

target = "thumbv7m-none-eabi"

[unstable]
build-std = ["core"]

[env]
# Set defmt log level
DEFMT_LOG = "trace"
